include: package:flutter_lints/flutter.yaml

linter:
  rules:
    - always_declare_return_types
    - avoid_empty_else
    - avoid_relative_lib_imports
    - avoid_types_as_parameter_names
    - empty_constructor_bodies
    - prefer_const_constructors
    - prefer_const_declarations
    - prefer_relative_imports

analyzer:
  errors:
    missing_required_param: error
    missing_return: error
    todo: ignore